version: '3'

services:
  strapi:
    container_name: strapi
    image: strapi
    restart: unless-stopped
    env_file: .env
    environment:
      DB_CLIENT: mysql
      DB_HOST: strapiDB
      DB_PORT: 3306
      DB_NAME: strapi
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      EXTRA_ARGS: ${EXTRA_ARGS}
      NODE_ENV: production
    ports:
      - 1337:1337
    networks:
      - strapi
    volumes:
      - ./app:/srv/app
    depends_on:
      - strapiDB

  strapiDB:
    container_name: strapiDB
    image: mysql:5.7
    restart: unless-stopped
    env_file: .env
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: strapi
    ports:
      - 3306:3306
    networks:
      - strapi
    volumes:
      - ./mysql:/var/lib/mysql

volumes:
  strapi-data:

networks:
  strapi:
    name: Strapi
    driver: bridge