version: '3'

services:
  strapi:
    container_name: strapi
    image: ghcr.io/holofansorchestra/strapi-docker:master
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: mysql2
      DATABASE_HOST: strapiDB
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      CUSTOM_COMMAND: yarn add @strapi/plugin-seo strapi-plugin-publisher strapi-plugin-sitemap strapi-plugin-cloudflare-pages strapi-plugin-responsive-image && yarn build
      NODE_ENV: production
    ports:
      - 1337:1337
    networks:
      - strapi
    volumes:
      - ./app/public:/srv/app/public
      - ./app/src/extensions:/srv/app/src/extensions
    depends_on:
      - strapiDB

  strapiDB:
    container_name: strapiDB
    image: mysql:latest
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: strapi
    ports:
      - 3306:3306
    networks:
      - strapi
    volumes:
      - ./mysql:/var/lib/mysql

networks:
  strapi:
    name: Strapi
    driver: bridge